### ISSUE TITLE
Delegating to OPA for Authz

### ISSUE THREAD

**Issue by maxott** [greenpau/caddy-auth-portal#135] opened 2021-06-12 02:13 UTC
Hi, I was just wondering if delegating to OPA for authorization would be possible? We use it for many other parts of the system and using a single place for managing authorization rules would greatly simplify things. 

Just checking.

Thanks

**Comment by greenpau** [comment] 2021-06-30 03:06
This is the duplicate of https://github.com/greenpau/caddy-auth-jwt/issues/73

**Closed by greenpau** 2021-06-30 03:06 UTC
