### ISSUE TITLE
How to use a single auth instance for multiple sites within a single domain?

### ISSUE THREAD

**Issue by sixtus** [greenpau/caddy-auth-portal#94] opened 2021-02-15 20:31 UTC
I am trying to run a single auth points for multiple hostnames in a domain.

```
auth.my.domain {
  route /auth* {
      auth_portal {
        cookie_domain my.domain
     }
  }
}
```

seems to do the trick.

However I am running into problems with the `primary` attribute. So far no combination seems to work. Do you have a working example?

I want to secure `a.my.domain` and `b.my.domain`, for login it should redirect to `auth.my.domain/auth` - all servers are configured in the same Caddyfile.

Thanks!
Hagen

**Comment by greenpau** [comment] 2021-02-15 20:41
@sixtus , please collect the information described [here](https://raw.githubusercontent.com/greenpau/caddy-auth-portal/main/.github/ISSUE_TEMPLATE/general-issue.md), because I need it to better understand the issue.

> However I am running into problems with the primary attribute. So far no combination seems to work. Do you have a working example?

Please see this [example](https://github.com/greenpau/caddy-auth-portal/issues/89#issuecomment-770310449).

Once I see your full config it will be easier to give you advice.

**Comment by sixtus** [comment] 2021-02-15 20:50
Thanks @greenpau - I basically got to the point of the linked example and now want to add another server, let's say `prometheus.example.com` and I just couldn't figure it out. But looks like a simply have to put a `jwt` in the 2nd server config. Somehow it only started working *after* I dared to ask for help :)

**Comment by greenpau** [comment] 2021-02-15 20:58
@sixtus , resolved? ;-) 

Asking a question after doing a little bit of research is almost always the right thing! Please do not hesitate asking in the future!

If the issue is resolved, please paste your final config :-)

**Comment by sixtus** [comment] 2021-02-15 21:16
```
(my-auth) {
  jwt {
    primary yes
    trusted_tokens {
      static_secret {
        token_name {$JWT_TOKEN_NAME}
        token_secret {$JWT_TOKEN_SECRET}
      }
    }
    auth_url https://example.com/auth/oauth2/azure
    allow roles everyone
  }
}

example.com {
  route /* {
    import my-auth
    redir https://example.com/auth/oauth2/azure 302
  }

  route /auth* {
    auth_portal {
      cookie_domain example.com
      ui {
        theme basic
      }
      jwt {
        token_name {$JWT_TOKEN_NAME}
        token_secret {$JWT_TOKEN_SECRET}
      }
      backends {
        azure_oauth2_backend {
          method oauth2
          realm azure
          provider azure
          client_id{$MICROSOFT_CLIENT_ID}
          client_secret {$MICROSOFT_SECRET}
          base_auth_url https://login.microsoftonline.de/{$MICROSOFT_TENANT}/oauth2/v2.0/
          metadata_url  https://login.microsoftonline.de/{$MICROSOFT_TENANT}/v2.0/.well-known/openid-configuration
          scopes openid email profile
        }
      }
    }
  }
}


proxy.example.com {
  route /* {
    jwt
    reverse_proxy http://127.0.0.1:5051
  }
}

static.example.com {
  root * /usr/share/caddy
  file_server

  route /* {
    jwt
  }
}
```

This example also shows how to use the Microsoft German Cloud, eol'd for end of 2021... good riddance, the changed urls are a pain.

**Comment by sixtus** [comment] 2021-02-15 21:19
the `(my-auth)` macro allows me to have the config at the top. And by including it into `auth.example.com` I get around the `primary` singleton.

**Comment by greenpau** [comment] 2021-02-15 21:28
@sixtus , thank you for posting the config! Closing?

**Closed** 2021-02-15 21:29 UTC

**Comment by chanux** [comment] 2021-03-25 05:29
I am trying to configure Github based oAuth for a static site following this example. I am getting in a redirect loop with multiples of following error in the log.

```
{"level":"error","ts":1616649370.6065226,"logger":"http.handlers.authentication","msg":"auth provider returned error","provider":"jwt","error":"no token found"}
```

Below is my Caddyfile

```
(auth) {
  jwt {
    primary yes
    allow roles everyone
    trusted_tokens {
      static_secret {
        token_name {$JWT_TOKEN_NAME}
        token_secret {$JWT_TOKEN_SECRET}
      }
    }
    auth_url https://auth.example.com/auth/oauth2/github
  }
}

https://auth.example.com {
  route /* {
    import auth
    redir https://auth.example.com/auth/oauth2/github 302
  }

  route /auth* {
    auth_portal {
      cookie_domain example.com
      ui {
        theme basic
      }
      jwt {
        token_name {$JWT_TOKEN_NAME}
        token_secret {$JWT_TOKEN_SECRET}
      }
      backends {
        github_oauth2_backend {
          method oauth2
          realm github
          provider github
          client_id {$GH_CLIENT_ID}
          client_secret {$GH_CLIENT_SECRET}
          scopes user
        }
      }
    }
  }
}

https://internal.example.com {
  root * /usr/share/caddy
  file_server

  route /* {
    jwt
  }
}
```

Anything I'm missing?

**Comment by greenpau** [comment] 2021-03-25 06:09
@chanux, next time please open a separate issue ;-)

move the following after /auth, not before. In essence, the below default route always preempts auth portal. So you are not getting there.

‘’’
  route /* {
    import auth
    redir https://auth.example.com/auth/oauth2/github 302
  }
‘’’

**Comment by chanux** [comment] 2021-03-25 12:01
Thanks for the reply. I have tried this but no luck. I'll work with it a little more and open a fresh issue with more info (hopefully).
